export const copy = {
  gameName: "NEON SWARM",
  tagline: "Defiende la línea de fotones. El enjambre no espera.",
  home: {
    context: "Escribe tu alias para entrar al hangar y despegar.",
    tip: "Tip: cada 1000 puntos ganas una vida extra. Solo una vez por cada múltiplo.",
    rotatingTips: [
      "Tip: mantén movimiento constante. Un cañón quieto es un blanco fácil.",
      "Tip: limpia una oleada completa para llevarte 500 puntos extra.",
      "Tip: los enemigos ámbar resisten un impacto más. Priorízalos si se acercan.",
      "Tip: pulsa H o F1 en cualquier momento para abrir la ayuda. El juego se pausa solo.",
      "Tip: A/D o flechas mueven. Espacio, W o flecha arriba disparan.",
      "Tip: M silencia el hangar. Los efectos son originales, no hay música de fondo.",
    ],
  },
  alias: {
    label: "Alias de piloto",
    placeholder: "Tu alias de piloto",
    suggestion: "Usa 3 a 20 caracteres: letras, números, espacio, - o _.",
    required: "El alias es obligatorio. Escribe un nombre para identificarte en el ranking.",
    tooShort: "El alias es demasiado corto. Prueba con al menos 3 caracteres.",
    tooLong: "El alias es demasiado largo. Quédate en 20 caracteres o menos.",
    invalidChars: "Ese alias tiene caracteres no válidos. Usa letras, números, espacio, guion o guion bajo.",
    ready: "Alias listo. Pulsa Iniciar partida cuando quieras despegar.",
  },
  actions: {
    start: "Iniciar partida",
    help: "Ver ayuda",
    pause: "Pausar",
    resume: "Reanudar",
    restart: "Reiniciar partida",
    playAgain: "Jugar de nuevo",
    backHome: "Volver al inicio",
    closeHelp: "Cerrar ayuda",
    quit: "Salir al hangar",
    stay: "Seguir en partida",
    soundOn: "Sonido: on",
    soundOff: "Sonido: off",
  },
  ranking: {
    title: "Mejores puntajes",
    empty: "Aún no hay puntajes locales. Sé la primera marca del hangar.",
    loading: "Cargando ranking local…",
    error: "No se pudo leer el ranking. Revisa que el servidor esté en marcha.",
    hint: "El ranking se guarda en este equipo. No necesitas cuenta.",
  },
  pause: {
    title: "Juego pausado",
    context: "El enjambre se detuvo. Reanuda cuando quieras.",
    tip: "Tip: pulsa P o Enter para reanudar. R reinicia. Q sale al hangar.",
  },
  quit: {
    confirmTitle: "Salir al hangar",
    context:
      "Esta partida no se guardará en el ranking. Puedes despegar de nuevo cuando quieras.",
    tip: "Tip: confirma con el botón o con Q. Seguir en partida te devuelve a la pausa.",
  },
  help: {
    title: "Centro de ayuda",
    context: "Objetivo, controles y reglas de supervivencia. El juego queda en pausa mientras lees.",
    objectiveTitle: "Objetivo",
    objective:
      "Controla el cañón inferior, dispara al enjambre y evita que cruce la línea de fotones. Destruye oleadas para subir de nivel y sumar puntos.",
    controlsTitle: "Controles",
    rulesTitle: "Vidas y puntaje",
    lives: "Empiezas con 3 vidas. Si un enemigo te impacta o llega al borde inferior, pierdes una.",
    extraLife: "Cada 1000 puntos ganas 1 vida extra. Se otorga una sola vez por cada múltiplo alcanzado.",
    waves: "Tip: las oleadas se vuelven más rápidas. Limpia pronto la formación y no dejes que descienda.",
    closeHint: "Cierra con el botón, Escape o H. Volverás al estado anterior (juego o pausa).",
  },
  controls: [
    { action: "Mover izquierda", primary: "Flecha izquierda", alt: "A" },
    { action: "Mover derecha", primary: "Flecha derecha", alt: "D" },
    { action: "Disparar", primary: "Espacio", alt: "W / Flecha arriba" },
    { action: "Pausar", primary: "P", alt: "Escape" },
    { action: "Reanudar", primary: "P", alt: "Enter" },
    { action: "Reiniciar", primary: "R", alt: "—" },
    { action: "Ayuda", primary: "H", alt: "F1" },
    { action: "Salir al hangar", primary: "Q", alt: "Solo en pausa" },
    { action: "Silenciar efectos", primary: "M", alt: "—" },
  ],
  hud: {
    score: "Puntaje",
    lives: "Vidas",
    wave: "Oleada",
    alias: "Piloto",
  },
  overlay: {
    hint: "← → mover  ·  Espacio disparar  ·  H ayuda",
    hintDetail: "También puedes usar A/D para mover y W o flecha arriba para disparar.",
  },
  gameOver: {
    title: "Fin de la partida",
    context: "El enjambre cruzó la línea. Tu marca queda registrada con tu alias.",
    lives: "Vidas restantes: 0",
    ranked: (position: number, total: number) =>
      `Quedaste #${position} de ${total} en el ranking local. Buen vuelo.`,
    entered: "Entraste al ranking local. Sigue empujando para subir posiciones.",
    missed: "Sigue practicando para entrar al top 10. El enjambre premia el ritmo constante.",
    tip: "Tip: prioriza enemigos bajos y no dejes de moverte mientras disparas.",
  },
  toasts: {
    extraLife: "Vida extra. Cruzaste otro múltiplo de 1000.",
    waveCleared: "Oleada limpia. +500 y el enjambre acelera.",
    scoreSaved: "Puntaje guardado en el ranking local.",
    scoreError:
      "No se pudo guardar el puntaje. Revisa que el servidor esté en marcha y vuelve a intentar.",
    rankingError: "No se pudo actualizar el ranking. Puedes seguir jugando igual.",
    hit: "Impacto. Te queda una vida menos. La oleada se reagrupa.",
  },
  nativeOnly: "Abre NEON SWARM en el navegador para usar teclado y el campo de juego.",
  a11y: {
    start: "Iniciar partida",
    help: "Abrir ayuda de controles y reglas",
    pause: "Pausar el juego",
    resume: "Reanudar el juego",
    restart: "Reiniciar la partida actual",
    playAgain: "Jugar otra partida con el mismo alias",
    backHome: "Volver a la pantalla inicial",
    closeHelp: "Cerrar la ayuda",
    alias: "Campo de alias del piloto",
    quit: "Salir al hangar sin guardar esta partida",
    stay: "Cancelar la salida y seguir en partida",
    soundOn: "Silenciar efectos de sonido",
    soundOff: "Activar efectos de sonido",
  },
} as const;
